### ISSUE TITLE
Change in when_collide between 1.0.0 and master

### ISSUE THREAD

**Issue by jlitola** [rubymotion-community/Joybox#42] opened 2013-07-05 10:35 UTC
I have been using structure like below in 1.0.0 with good success (simplified example):

```
body = @world.new_body position: position, type: KDynamicBodyType do
    ...
end

body.define_singleton_method :object_type do
    'block'
end

@world.when_collide body do |target, is_touching|
    if target.respond_to? :object_type
        ... do something depending on the object_type
    end
end
```

I noticed that master had support to additional Box2D methods, so I switched over to master, but there the similar approach doesn't work there. I also switched code to use setUserData+userData as it was now supported in master, but userData on the target object is always nil.

Has there been some regression, or should I switch to some other approach for identifying the game objects from the body?

**Comment by NSCoder** [comment] 2013-07-06 04:58
Hello Juha!

We have to make some changes on the body in the light of increasing memory utilization and performance, the master repository version does not return anymore the same pointer of the body in the callback of the collision. But in the version just updated (sha: f03db9ea59a8feeb617139351c02545f30201913) we tackle that problem in the following way:

1) When you ask of equalty using body == body, internally is calling the b2Body (c++ Box2D Body) to check for the comparison. So we are cool here.

2) The other thing was the disability of saving information in the body itself, giving you the problem that you are mentioning (thanks for the report!). I just create a patch for tackling this one, and is the following:

``` ruby
body_ground = @world.create_body position:[1024, 1]
body_ball = @world.create_body position: [100, 100]
body_ball[:type] = 'Green Ball'

world.when_collide body_ground do |collision_body, is_touching|
  p collision_body[:type] #This should print 'Green Ball'
end
```

We are saving the information inside the b2Body using the userData property, also we are thinking using it as well for other more advance purposes ;). 

Also I look into the example and you now can ask a body about its type using body.type == Body::Static, I am sorry we don't have documentation for this yet (Its planned for the release) but if you need more information you can look at the specs or write us another issue.

I hope it helps :)

Thanks for the report and don't forget to pull the latest version

**Comment by jlitola** [comment] 2013-07-07 15:50
Thanks for the detailed explanation.

I tried using the approach you described, but I now seem to be getting error when linking the application with HEAD version:

```
Cannot define method `vertices' because no Objective-C stub was pre-compiled for types `^{CGPoint=ff}@:'. Make sure you properly link with the framework or library that defines this message.
```

I'm using master version with Bundler and following definition:

```
gem 'joybox', :git => 'git@github.com:rubymotion/Joybox.git'
```

Should I be using some other approach when using version from Git?

**Comment by NSCoder** [comment] 2013-07-08 03:12
Hello Juha,

I think is a mix up version problem, i made some test and i hope the following will fix the problem:

1) Uninstall joybox gem:

```
$ gem uninstall joybox -a
```

2) Update your Gemspec file to:

```
gem 'joybox', :git => 'git@github.com:rubymotion/Joybox.git', :branch => 'master'
```

3) Finally, clean and rebuild:

```
$ rake clean
$ rm .repl_history
$ rake
```

Please tell me if it work :)

**Comment by jlitola** [comment] 2013-07-08 14:21
Thanks again for your support. Those instructions helped, although I don't know why as I had done all the steps before, except for adding :branch=>'master'. 

I now tested body[:type] approach, but as soon as I refer to body[:type] in the collision handler, the application crashes. Seems that accessing the body.userData gives:

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x2404c704
```

in body.rb:134.

I tried tracing the issue, and it seems to me that the issue could be in the joybox-box2d, where Box2D/Callback/B2DContactListener.mm creates new instance of B2DBody without setting the userData. Shouldn't it just return the existing B2DBody instance with

```
(B2DBody *) firstBoxBody->GetUserData()
```

That would also allow more efficient handling in setup_collision_listener. Or is there something I'm overlooking? Unfortunately I don't know how I should compile and test with modified joybox-box2d, so couldn't verify the change. Currently also objects in @listening_bodies are not removed when you call destroy_body. This will cause performance issues if lot of objects get created and destroyed.

Additionally I noticed that there is bug in the newly introduced spec for checking the userData value

```
diff --git a/spec/motion/joybox/physics/world_spec.rb b/spec/motion/joybox/physics/world_spec.rb
index 028caa5..58f3613 100644
--- a/spec/motion/joybox/physics/world_spec.rb
+++ b/spec/motion/joybox/physics/world_spec.rb
@@ -145,7 +145,7 @@ describe Joybox::Physics::World do
     world.when_collide body_one do |collision_body, is_touching|
       collision_notified = true
       collision_body.should == body_two
-      collision_body[:message] = 'Second Body'
+      collision_body[:message].should == 'Second Body'
       is_touching.should == true
     end
```

**Comment by NSCoder** [comment] 2013-07-09 03:47
I have been able to reproduce the problem, here are the findings:

When the Body is initialized using the world to create it, two entities are created the b2Body (c++) and Body (ruby - obj-c), the b2Body has the property userData inside it to hold objects for later purpose. So really when you are assigning a value to the user data (in this case the hash) it saves it inside the c++ object, this will allow to have different instance of the Body accessing the same userData just calling the b2Body inside them.

But the problem was that the hash that we were assigning to the userData property was released by the garbage collector, so when we try to access it... boom! I made some changes to manage the memory from the obj-c side and test it in the same environment that previously have the problem and now i think is fixed.

I hope that if you update it will work for you as well!

About the @listening_bodies you are totally right, it will be fixed in the next commit!

About the spec, I probably misunderstood what you mean. But it pass in the previous executions because the assignment and the read were in the same method, so the garbage collector wasn't been able to recollect the hash at that time.

Sorry for all the inconveniences that this cause, and thank you for taking the time to track this bug down!

JK

**Comment by jlitola** [comment] 2013-07-09 04:33
I can confirm that it now works properly for me also. Thanks!

Just for the curiosity, I didn't see any changes on the Joybox-Box2D side, and the changes on Joybox didn't address these memory issues. Is there still some other component that is in use, or are the changes on the Joybox-Box2d just not pushed yet? I would like to have better understanding, as I think that I need to be looking through the source code also in the future :)

With the spec I just mean that it is not currently checking if the message is correct, instead it is re-assigning the message in when_collide on line 148 of world_spec.rb.

**Comment by NSCoder** [comment] 2013-07-09 04:45
Thats great! It feels good to se that is working :)

Sorry! I just pushed the changes on the Joybox-Box2D, I have to do some test anytime it changes, most of them performance just to make sure it does not break anything ;)

Oh I see! I change the like, thanks!

**Comment by NSCoder** [comment] 2013-08-06 16:21
Hello Juha!

This is now applied on the Joybox version 1.1.0, thank you for all the feedback

Cheers

JK

**Closed as completed by NSCoder** 2013-08-06 16:21 UTC
