### ISSUE TITLE
SpriteBatch doesn't seems to work

### ISSUE THREAD

**Issue by yestoall** [rubymotion-community/Joybox#11] opened 2013-04-29 08:27 UTC
i'm trying to load a texture package file and always i have the same error:
sprite.rb:14:in `new:': undefined method`position=' for nil:NilClass (NoMethodError)

**Comment by NSCoder** [comment] 2013-04-29 15:58
Thank you!

We have different versions of the SpriteBatch in the gem and in the repository, can you help me telling me in which version this is happening? So we can have a better solution to it ;)

**Comment by yestoall** [comment] 2013-04-29 16:29
i'm using gem version.
compiling with gem version i have this error.
with the repository version i don't have a compile error but nothing appears on the screen.

with cocos2d framework it works but not with joybox DSL.

**Comment by yestoall** [comment] 2013-04-29 17:26
sorry, now works... i was missing:
CCSpriteFrameCache.sharedSpriteFrameCache.addSpriteFramesWithFile("letras.plist")

**Comment by NSCoder** [comment] 2013-04-29 17:42
Oh! is nice to hear that is working now!

The next version of the DSL will have full support for the SpriteBatches, I think it will be released this week :)

**Comment by yestoall** [comment] 2013-04-29 17:46
ok, works... 

```
CCSpriteFrameCache.sharedSpriteFrameCache.addSpriteFramesWithFile("letras.plist")

sprite_cache = SpriteBatch.new file_name: "letras.plist"
self << sprite_cache

sprite = Sprite.new frame_name: "B_01.png", position: [150,100]
self << sprite
```

but now SpriteBatch is not needed... so SpriteBatch is not working

**Comment by NSCoder** [comment] 2013-04-29 17:49
I think the problem is:

``` ruby
# Change this
self << sprite

# For this
sprite_cache << sprite
```

**Comment by yestoall** [comment] 2013-04-29 17:54
doesn't work

but is i use
    CCSpriteFrameCache.sharedSpriteFrameCache.addSpriteFramesWithFile("letras.plist")

i don't need to use SpriteBatch
    sprite_cache = SpriteBatch.new file_name: "letras.plist"
    self << sprite_cache

**Comment by NSCoder** [comment] 2013-04-29 18:05
Yes it will work, but you are still drawing the sprites one by one :(

Here is a code for one of the upcoming examples (It will work if you are using the repository version):

``` ruby
sprite_batch = SpriteBatch.new file_name: 'animation/AnimBear.png'

self << sprite_batch


SpriteFrameCache.frames.add file_name: 'animation/AnimBear.plist'

sprite = Sprite.new frame_name: 'bear1.png',
                        position: [Screen.half_width, Screen.half_height]

sprite_batch << sprite
```

I hope it helps ;)

**Comment by yestoall** [comment] 2013-04-29 18:17
an example is better than anything.
now i understand and works for me.

is fun and sometimes "hard" to learn cocos2d and joybox at the same time.
is a good example to understand why we love ruby and rubymotion and why i hate objectiveC  ;)

thanks a lot.
i'm playing with some examples too.

**Comment by NSCoder** [comment] 2013-04-29 18:29
Awesome! Yeah I remember you from twitter! I hope we can see some of your examples soon :)

Yes, it will be a little more complicated to learn the two of them at the same time :) but actually you are doing an amazing work already learning about the SpriteBatch ;). I hope with more examples and tutorials we can make it easier for everybody to learn it.

Anyway if you have questions or need some guidance in the learning process you can always ping me :)

**Comment by yestoall** [comment] 2013-04-29 18:33
ok, thanks for your work.
in spanish is better too ;)

maybe spanish is better by email ;)
nacho@yestoall.com

**Comment by NSCoder** [comment] 2013-04-29 18:44
Super bien! Te paso mi gtalk juanjokaram at gmail punto com

**Closed as completed by NSCoder** 2013-04-29 18:44 UTC
